### ISSUE TITLE
NoMethodError: undefined method `to_sym' for nil:NilClass

### ISSUE THREAD

**Issue by ampledata** [poise/application#65]
details TK, but this morning we generated this stacktrace: 

```
Generated at 2017-01-10 12:09:17 -0800
NoMethodError: undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
/var/cache/chef/cookbooks/poise/files/halite_gem/poise/helpers/resource_subclass.rb:38:in `subclass_providers!'
/var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:43:in `<class
:Resource>'
/var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:39:in `<modul
e:ApplicationCookbookFile>'
/var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:24:in `<modul
e:Resources>'
/var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:21:in `<modul
e:PoiseApplication>'
/var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:20:in `<top (
required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources.rb:18:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/cache/chef/cookbooks/application/files/halite_gem/poise_application/cheftie.rb:17:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/cache/chef/cookbooks/application/libraries/default.rb:19:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:191:in `load'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:191:in `block in load_libraries_from_cookbook'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:188:in `each'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:188:in `load_libraries_from_cookbook'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:99:in `block in compile_libraries'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:98:in `each'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:71:in `compile'
/usr/lib/ruby/vendor_ruby/chef/run_context.rb:96:in `load'
/usr/lib/ruby/vendor_ruby/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
/usr/lib/ruby/vendor_ruby/chef/client.rb:256:in `setup_run_context'
/usr/lib/ruby/vendor_ruby/chef/client.rb:454:in `run'
/usr/lib/ruby/vendor_ruby/chef/application.rb:271:in `block in fork_chef_client'
/usr/lib/ruby/vendor_ruby/chef/application.rb:259:in `fork'
/usr/lib/ruby/vendor_ruby/chef/application.rb:259:in `fork_chef_client'
/usr/lib/ruby/vendor_ruby/chef/application.rb:225:in `block in run_chef_client'
/usr/lib/ruby/vendor_ruby/chef/local_mode.rb:39:in `with_server_connectivity'
/usr/lib/ruby/vendor_ruby/chef/application.rb:213:in `run_chef_client'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:402:in `block in interval_run_chef_client'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:392:in `loop'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:392:in `interval_run_chef_client'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:382:in `run_application'
/usr/lib/ruby/vendor_ruby/chef/application.rb:60:in `run'
/usr/bin/chef-client:26:in `<main>'
```

```
[2017-01-10T12:16:14-08:00] INFO: Forking chef instance to converge...
[2017-01-10T12:16:14-08:00] INFO: *** Chef 12.3.0 ***
[2017-01-10T12:16:14-08:00] INFO: Chef-client pid: 13011
[2017-01-10T12:16:18-08:00] INFO: Run List is [role[tomato]]
[2017-01-10T12:16:18-08:00] INFO: Run List expands to [apt, avahi, chef-client, sudo, poise-python, ntp, postfix, slackmail,
undef-base-cb::users, undef-sensu, undef-sensu::ntp, chef-splunk, undef-base-cb::splunk, undef-sensu::splunk, nginx, undef-ba
se-cb, undef-sensu::master, undef-sensu::rabbitmq, undef-sensu::redis, redisio, redisio::enable]
[2017-01-10T12:16:18-08:00] INFO: Starting Chef Run for tomato
[2017-01-10T12:16:18-08:00] INFO: Running start handlers
[2017-01-10T12:16:18-08:00] INFO: Start handlers complete.
[2017-01-10T12:16:20-08:00] INFO: Loading cookbooks [apt@5.0.1, compat_resource@12.16.3, avahi@1.0.2, chef-client@7.0.3, cron
@3.0.0, logrotate@2.1.0, windows@2.1.1, ohai@4.2.3, sudo@3.3.0, poise-python@1.5.1, poise@2.7.1, poise-languages@2.0.4, poise
-archive@1.3.0, ntp@3.3.1, postfix@4.0.0, slackmail@0.1.2, ark@2.2.1, build-essential@7.0.3, seven_zip@2.0.2, mingw@1.2.4, ap
plication_python@4.0.0, application@5.1.0, poise-service@1.4.2, supervisor@0.4.12, python@1.4.6, yum-epel@2.1.1, application_
git@1.1.0, git@5.0.1, dmg@3.0.0, undef-base-cb@2.0.1, users@4.0.3, undef-sensu@2.0.42, sensu@3.1.2, yum@3.13.0, ms_dotnet@3.1
.0, rabbitmq@4.10.0, erlang@4.1.0, yum-erlang_solutions@1.0.3, dpkg_autostart@0.2.0, redisio@2.5.0, ulimit@0.4.0, uchiwa@1.2.
0, chef-splunk@1.6.6, chef-vault@2.1.1, nginx@1.8.0, runit@1.8.0, packagecloud@0.2.5]

================================================================================
Recipe Compile Error in /var/cache/chef/cookbooks/application/libraries/default.rb
================================================================================

NoMethodError
-------------
undefined method `to_sym' for nil:NilClass
Did you mean?  to_s

Cookbook Trace:
---------------
  /var/cache/chef/cookbooks/poise/files/halite_gem/poise/helpers/resource_subclass.rb:38:in `subclass_providers!'
  /var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:43:in `<
class:Resource>'
  /var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:39:in `<
module:ApplicationCookbookFile>'
  /var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:24:in `<
module:Resources>'
  /var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:21:in `<
module:PoiseApplication>'
  /var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources/application_cookbook_file.rb:20:in `<
top (required)>'
  /var/cache/chef/cookbooks/application/files/halite_gem/poise_application/resources.rb:18:in `<top (required)>'
  /var/cache/chef/cookbooks/application/files/halite_gem/poise_application/cheftie.rb:17:in `<top (required)>'
  /var/cache/chef/cookbooks/application/libraries/default.rb:19:in `<top (required)>'

Relevant File Content:
----------------------
/var/cache/chef/cookbooks/poise/files/halite_gem/poise/helpers/resource_subclass.rb:

 31:            resource_name ||= self.resource_name
 32:            superclass_resource_name ||= if superclass.respond_to?(:resource_name)
 33:              superclass.resource_name
 34:            elsif superclass.respond_to?(:dsl_name)
 35:              superclass.dsl_name
 36:            else
 37:              raise Poise::Error.new("Unable to determine superclass resource name for #{superclass}. Please specify n
ame manually via subclass_providers!('name').")
 38>>           end.to_sym
 39:            # Deal with the node maps.
 40:            node_maps = {}
 41:            node_maps['handler map'] = Chef.provider_handler_map if defined?(Chef.provider_handler_map)
 42:            node_maps['priority map'] = Chef.provider_priority_map if defined?(Chef.provider_priority_map)
 43:            # Patch anything in the descendants tracker.
 44:            Chef::Provider.descendants.each do |provider|
 45:              node_maps["#{provider} node map"] = provider.node_map if defined?(provider.node_map)
 46:            end if defined?(Chef::Provider.descendants)
 47:            node_maps.each do |map_name, node_map|


[2017-01-10T12:16:20-08:00] ERROR: Running exception handlers
[2017-01-10T12:16:20-08:00] ERROR: Exception handlers complete
[2017-01-10T12:16:20-08:00] FATAL: Stacktrace dumped to /var/cache/chef/chef-stacktrace.out
[2017-01-10T12:16:20-08:00] INFO: Sending resource update report (run-id: c1467eec-7c4c-4d44-a09c-2685816bb1b0)
[2017-01-10T12:16:21-08:00] ERROR: undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
[2017-01-10T12:16:21-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by coderanger** [comment]
Odd, the error above isn't raising so it's using either `resource_name` or `dsl_name` but one of those is returning nil. Your stack trace looks a bit odd, are you using a custom-built installer?

**Comment by ampledata** [comment]
"custom built installer"? for chef-client?

**Comment by coderanger** [comment]
You're installing from the distro packages, this is not recommended. Can you repro this on the normal omnibus installer for 12.3.0? Distros have a habit of applying their own patches which I cannot test against.

**Comment by ampledata** [comment]
that fixed it, thanks noah!
